server:
  port: 8086

spring:
  application:
    name: ms-franchise-service
  data:
    mongodb:
      uri: mongodb://mongodb:27017/franchise_db

management:
  endpoints:
    web:
      exposure:
        include: health,info

appDescription: "Prueba técnica ms-franchise-service"
appVersion: "1.0.0"
